### ISSUE TITLE
Cappy wifi

### ISSUE THREAD

**Issue by CtorW** [FLOCK4H/Cappy#1]
i test in my android device and after i connect into cappy wifi no notification show to go in cappy html captive portal on http://10.0.0.15:80, how to i fix this ,thankyou

**Comment by FLOCK4H** [comment]
**You must have at least two adapters**,

- one providing the internet (its not used anyways but for 'the notification to pop up' it's necessary), 
- one for hosting the captive portal

Additionally make sure that **hostapd, lighttpd, and dnsmasq** are installed manually:

```
  $ sudo apt-get install hostapd lighttpd dnsmasq
```

Let me know if this helps!

**Comment by CtorW** [comment]
so this is my problem ("one providing the internet (its not used anyways but for 'the notification to pop up' it's necessary),") thankyouu!
