### ISSUE TITLE
Problem with wifi name

### ISSUE THREAD

**Issue by Sorzusu** [FLOCK4H/Cappy#2]
I am conducting a social experiment on my familly to see if they would trust an open network, so i am looking for a way to rename the wifi

**Comment by FLOCK4H** [comment]
You can rename the WiFi by editing the config.

**Comment by Sorzusu** [comment]
It may sound kind of silly, but how ? 😅

**Comment by FLOCK4H** [comment]
```
  $ sudo nano /etc/hostapd/hostapd.conf
```
interface=eth0
driver=nl80211
ssid=HERE
hw_mode=g
channel=10
[...]

**Comment by Sorzusu** [comment]
Thanks man ! Keep up the great work !

**Comment by RacerX22288** [comment]
A follow up on this one:  Each time I try to re-name the ssid it gets reverted back to Cappy! up 'start' ... any way to prevent this?
