### ISSUE TITLE
Revisiting AP ssid

### ISSUE THREAD

**Issue by RacerX22288** [FLOCK4H/Cappy#3]
Hello and sorry...but I know you've given guidance on altering the ssid through the hostapd.conf file in the past, yet it seems that when I run the script if overwrites any said I've entered with Cappy! ... I know I'm missing something super simple...but a little nudge in the right direction would be very much appreciated. Thanks!

**Comment by FLOCK4H** [comment]
Did you try to use Freeway where Cappy is built-in and also a lot more customizable? This repo is not under active development. To change from default Cappy! name, one should find mention about writing to hostapd.conf file in source code of this repo and modify it.

Additionally, make sure that hostapd config is located under /etc/hostapd.
